# Generated by Django 4.1.4 on 2023-06-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userlogo_useraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='country',
            new_name='county',
        ),
    ]
