# Generated by Django 4.1.4 on 2023-06-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_country_useraddress_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogo',
            name='photo',
        ),
        migrations.AddField(
            model_name='userlogo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='logo'),
        ),
    ]
